In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3], dtype='float32')
print(x)
print(x.shape)
print(x[0])

[1. 2. 3.]
(3,)
1.0


In [3]:
z = np.array([[1,2,3], [4, 5, 6]], dtype='float32')
print(z)
print(z.shape)
print(z[1, 1])

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
5.0


In [4]:
y = np.array([[1, 2, 3]], dtype='float32')
print(y)
print(y.shape)
print(y[0, 1])

[[1. 2. 3.]]
(1, 3)
2.0


In [5]:
w = np.array([[[1,2,3], [4, 5, 6]],
              [[11,12,13], [14, 15, 16]],
              [[21,22,23], [24, 25, 26]]]
             , dtype='float32')
print(w)
print()
print("Shape:", w.shape)
print()
print("Array element:", w[2, 0, 1])

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[11. 12. 13.]
  [14. 15. 16.]]

 [[21. 22. 23.]
  [24. 25. 26.]]]

Shape: (3, 2, 3)

Array element: 22.0


In [6]:
x = np.linspace(-2, 2, 9)
print(x.shape)
print(x)

(9,)
[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]


In [7]:
x = np.random.normal(10, 90, 10000)
print(x.shape)
print(x[0:10])

(10000,)
[ -89.13571889 -101.10308691  207.18132587 -116.6903173   -44.7865297
   52.97370708  -28.31354288  -95.55838783   17.31082807  148.68055641]


In [8]:
shape = (2, 3)
x = np.zeros(shape, dtype = 'float32')
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
shape = (3, 2)
y = np.ones(shape, dtype = 'float32')
print(y)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
w = np.array([[[1,2,3], [4, 5, 6]],
              [[11,12,13], [14, 15, 16]],
              [[21,22,23], [24, 25, 26]]]
             , dtype='float32')
print(w.shape[0], w.shape[1], w.shape[2])

3 2 3


In [11]:
y = np.array([[1, 2, 3]], dtype='float32')
print(y)
print(y.shape)
print(y[0, 1])

[[1. 2. 3.]]
(1, 3)
2.0


In [12]:
y1D = y.ravel()
print(y1D)
print(y1D.shape)
print(y1D[1])

[1. 2. 3.]
(3,)
2.0


In [13]:
y1Dv2 = y.reshape(3,)
print(y1Dv2)
print(y1Dv2.shape)
print(y1Dv2[1])

[1. 2. 3.]
(3,)
2.0


In [14]:
z1 = np.array([[1,2,3], [4, 5, 6]], dtype='float32')
z2 = np.array([[7,8,9], [10, 11, 12]], dtype='float32')
z = z1 + z2
print(z)

[[ 8. 10. 12.]
 [14. 16. 18.]]


In [15]:
z = np.sqrt(z1)
print(z)

[[1.        1.4142135 1.7320508]
 [2.        2.236068  2.4494898]]


In [16]:
print(z2.min())
print(z2.sum())
print(z2.mean())

7.0
57.0
9.5


In [17]:
z2 = np.array([[7,8,9], [10, 11, 12]], dtype='float32')
print(np.sum(z2, axis=1))

[24. 33.]


In [18]:
z1 = np.array([[1,2,3], [4, 5, 6]], dtype='float32')
z2 = np.array([[1,2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype='float32')
z = np.matmul(z1, z2)
print(z1.shape, z2.shape)
print(z.shape)

(2, 3) (3, 4)
(2, 4)


In [19]:
z = np.array([[1,2], [3, 4]], dtype='float32')
zinv = np.linalg.inv(z)
id = np.matmul(z, zinv)
print(id)

[[1. 0.]
 [0. 1.]]
